-- Регистрация сетевых строк
if SERVER then
    util.AddNetworkString("GModsaken_UpdateStamina")
    util.AddNetworkString("GModsaken_UpdateHealth")
    util.AddNetworkString("GModsaken_UpdateArmor")
    util.AddNetworkString("GModsaken_UpdateRound")
    util.AddNetworkString("GModsaken_UpdateGameState")
    util.AddNetworkString("GModsaken_UpdatePlayerRole")
    util.AddNetworkString("GModsaken_UpdateCharacter")
    util.AddNetworkString("GModsaken_UpdateWeapon")
    util.AddNetworkString("GModsaken_UpdateMusic")
    util.AddNetworkString("GModsaken_UpdateMusicVolume")
    util.AddNetworkString("GModsaken_UpdateMusicEnabled")
    util.AddNetworkString("GModsaken_PlayMusic")
    util.AddNetworkString("GModsaken_StopMusic")
    util.AddNetworkString("GModsaken_SwitchMusic")
    util.AddNetworkString("GModsaken_UpdateQuests")
    util.AddNetworkString("GModsaken_UpdateQuestProgress")
    util.AddNetworkString("GModsaken_UpdateQuestStats")
    util.AddNetworkString("GModsaken_KillAnimation")
    util.AddNetworkString("GModsaken_KillAnimationEnd")
    util.AddNetworkString("GModsaken_SpawnProp")
    util.AddNetworkString("GModsaken_PropSpawned")
    util.AddNetworkString("GModsaken_PropDisintegrated")
    util.AddNetworkString("GModsaken_ClearProps")
    util.AddNetworkString("GModsaken_BlindPlayer")
    util.AddNetworkString("GModsaken_StartChaseMusic")
    util.AddNetworkString("GModsaken_StopChaseMusic")
    print("[GModsaken] Network strings registered")
end 